# Generated by Django 5.0 on 2023-12-28 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
