# Generated by Django 5.0 on 2023-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0003_userpost_dislikes_userpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
