# Generated by Django 5.0 on 2023-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0004_alter_userpost_dislikes_alter_userpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='who_disliked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='who_liked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
