# Generated by Django 5.0 on 2024-01-02 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0005_userpost_who_disliked_userpost_who_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_text', models.CharField(max_length=500)),
                ('user_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uno.userpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
